server:
  port: ${PORT:40101}
  servlet:
    context-path: /auth
spring:
  application:
    name: lzshzz-service-ucenter-auth
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: common,eureka,ribbon,redis,mysql  # 引入公共插件
  thymeleaf:
    prefix: classpath:/templates/ #
    suffix: .html # 构建URL时附加查看名称的后缀.
    cache: false #<!-- 关闭thymeleaf缓存 开发时使用 否则没有实时画面-->
    mode: LEGACYHTML5 #模板编码
    check-template-location: true # 检查模板是否存在，然后再呈现
    enabled: true #启用MVC Thymeleaf视图分辨率
  mvc:
    static-path-pattern: /** # 静态文件请求匹配方式
  resources:
    static-locations: classpath:/static/ # 修改默认的静态寻址资源目录

auth:
  tokenValiditySeconds: 30  #token存储到redis的过期时间(天)
  clientId: lzshzz
  clientSecret: 5b80076a74ca62e71f7139d9479f23bb
  cookieDomain: java.qzl.cn
  cookieMaxAge: -1 #浏览器关闭，cookie就会失效
encrypt:
  key-store:
    location: classpath:/lzshzz.keystore
    secret: lzshzz
    alias: lzshzz
    password: lzshzz
#不加这个你页面死也不给你跳转,可能是新版本的原因吧，我也不知道
security:
  oauth2:
    client:
      registered-redirect-uri: http://www.baidu.com
