server:
  port: ${PORT:40101}
  servlet:
    context-path: /auth
spring:
  application:
    name: lzshzz-service-ucenter-auth
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: common,eureka,ribbon  # 引入公共插件
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/app_rest?serverTimezone=UTC&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&characterEncoding=utf8}
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  thymeleaf:
    prefix: classpath:/templates/ #
    suffix: .html # 构建URL时附加查看名称的后缀.
    cache: false #<!-- 关闭thymeleaf缓存 开发时使用 否则没有实时画面-->
    mode: LEGACYHTML5 #模板编码
    check-template-location: true # 检查模板是否存在，然后再呈现
    enabled: true #启用MVC Thymeleaf视图分辨率
  mvc:
    static-path-pattern: /** # 静态文件请求匹配方式
  resources:
    static-locations: classpath:/static/ # 修改默认的静态寻址资源目录

auth:
  tokenValiditySeconds: 30  #token存储到redis的过期时间(天)
  clientId: lzshzz
  clientSecret: 5b80076a74ca62e71f7139d9479f23bb
  cookieDomain: java.zdww.cn
  cookieMaxAge: -1 #浏览器关闭，cookie就会失效
encrypt:
  key-store:
    location: classpath:/lzshzz.keystore
    secret: lzshzz
    alias: lzshzz
    password: lzshzz
#不加这个你页面死也不给你跳转,可能是新版本的原因吧，我也不知道
security:
  oauth2:
    client:
      registered-redirect-uri: http://www.baidu.com
