# tomcat 的一些配置
server:
  tomcat:
    accept-count: 1000
    max-connections: 10000 #最大可被连接数，默认为10000
    max-threads: 800  #最大工作线程数
    min-spare-threads: 100 #最小工作线程数

#配置日志信息
logging:
  config: classpath:config/logback-spring.xml
  path: ${LOG_PATH:d:/lzshzz_logs}
#配置swagger开关信息
swagger:
  enabled: true
# 数据同步配置
data:
  url: http://10.18.32.232:9001/ # 数据同步默认地址
  open: true    # 是否开启数据同步
# 配置需要放行的地址
except:
  path: /auth/userlogin,/auth/getCheckNum,/auth/checkNum,/auth/sendSms,/auth/sendNotice,/auth/getApkVersion,/auth/getYszc,/file/show,/file/playVideo,/file/downloadApk,/auth/css/**
  service_path: /v2/api-docs,/swagger-resources/configuration/ui,/swagger-resources,/swagger-resources/configuration/security,/swagger-ui.html,/webjars/**
  auth_path: /userlogin, /userlogout, /getUserInfo, /getCheckNum,/saveLog,/autoLogin,/deleteRedis,/checkNum,/sendNotice,/getApkVersion,/getYszc,/downloadApk,/css/**,/show,/playVideo,/downloadApk
