server:
  port: ${PORT:60101}
  servlet:
    context-path: /file
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: lzshzz-service-file
  profiles:
    active: common,eureka  # 引入公共插件
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/app_rest?serverTimezone=UTC&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&characterEncoding=utf8}
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#ftp  服务配置
file:
  ftpHost: 10.18.100.205
  ftpUserName: lzshzz
  ftpPassword: Lzshzz_2019
  ftpPort: 21
  filepath: D\:\\  #文件上传地址