server:
  port: ${PORT:60101}
  servlet:
    context-path: /file
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: lzshzz-service-file
  profiles:
    active: common,eureka,mysql  # 引入公共插件
#ftp  服务配置
file:
  ftpHost: 10.18.100.205
  ftpUserName: lzshzz
  ftpPassword: Lzshzz_2019
  ftpPort: 21
  filepath: D\:\\  #文件上传地址