server:
  port: ${PORT:31002}
  servlet:
    context-path: /app
spring:
  application:
    name: app
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://10.18.100.57:3306/lzshzz?useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&characterEncoding=utf8}
      username: lzshzz
      password: Hzz_2019
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
swagger:
  enabled: true
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔,http://localhost:50102/eureka/
      defaultZone: ${EUREKA_SERVER:http://10.18.100.205:10101/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:10.18.28.69}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
mybatis:
  type-aliases-package: com.zdww.lashzz.model
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql